# Site settings
author: James Taylor Johnson
title: From Zero to Sixty
header-img: img/home-bg.png
email: jtaylorjohnson@gmail.com
copyright_name: James Taylor Johnson
description: > # this means to ignore newlines until "baseurl:"
  The Path to Becoming a Software Engineer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jtaylorjohnson

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
